[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[[bin]]
name = "aoc2024"
bench = false

[[bench]]
name = "bench"
harness = false

[dependencies]
ahash = "0.8.11"
criterion = { version = "0.5.1", features = ["html_reports"] }
itertools = "0.13.0"
